name: Rust

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  mac-build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Build termbg-li
        run: cargo build --release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/termbg-cli
